apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  namespace: {{ .Release.Name }}-ns
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-svc
          servicePort: {{ .Values.port }}